### ISSUE TITLE
Persistent progress_bar after interrupting `map` loop in the middle

### ISSUE THREAD

**Issue by brunomioto** [tidyverse/purrr#1024]
I'm using it in a personal function, but will try to reproduce it asap.
I run the function, progress bars appears and everything works fine (it even disappears as expected).
But if I interrupt this map loop with `Esc`, the progress bar keeping appearing after every code I ran

**Comment by brunomioto** [comment]
```
library(purrr)
  
example_fun <- function(query){
  
    
    res <- purrr::map(query, .f = function(x) {
      Sys.sleep(1)
    }, .progress = list(format = "Query {cli::pb_current+1}/{cli::pb_total} | {cli::pb_bar} { {paste0(round({{cli::pb_current}/{cli::pb_total}}*100),'%')} } [{cli::pb_elapsed}]",
                        show_after = 0,
                        clear = TRUE)
    )%>%
      purrr::list_rbind()

  return(res)
  
}

#First example - Pressed Esc in 33%
example_fun(c("a","b","c"))

#Second example - Run normally
example_fun(c("a","b","c"))
```



![image](https://user-images.githubusercontent.com/10459392/208961753-4d47355c-2afa-4652-b09e-a2a1698be0c3.png)

**Comment by brunomioto** [comment]
``` r
packageVersion("cli")
#> [1] '3.4.1'
sessioninfo::platform_info()
#>  setting  value
#>  version  R version 4.1.1 (2021-08-10)
#>  os       Windows 10 x64 (build 19044)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language (EN)
#>  collate  Portuguese_Brazil.1252
#>  ctype    Portuguese_Brazil.1252
#>  tz       America/Sao_Paulo
#>  date     2022-12-21
#>  pandoc   2.19.2 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)
```

<sup>Created on 2022-12-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
I'd start by restarting R and installing the latest cli (3.5).

**Comment by DavisVaughan** [comment]
<img width="467" alt="Screen Shot 2022-12-21 at 6 14 41 PM" src="https://user-images.githubusercontent.com/19150088/209020942-3f40691f-e04d-4cf8-8446-91a9156d99ed.png">

I can reproduce this too actually. With CRAN cli

**Comment by DavisVaughan** [comment]
I wonder if it is because this `cli_progress_done()` is never hit?
https://github.com/tidyverse/purrr/blob/54546b6bf938c54da4d232061db2fc91b1d5923c/src/map.c#L46

Because of this `R_CheckUserInterrupt()` call?
https://github.com/tidyverse/purrr/blob/54546b6bf938c54da4d232061db2fc91b1d5923c/src/map.c#L32

**Comment by DavisVaughan** [comment]
Another way to reproduce is to cause a `stop()` on, say, the 2nd index. And then call the function again but without the `stop()`

```r
library(purrr)

example_fun <- function(query){
  
  
  res <- purrr::map(query, .f = function(x) {
    if (x == "b") {
      stop("oh no")
    }
  }, .progress = list(format = "Query {cli::pb_current+1}/{cli::pb_total} | {cli::pb_bar} {cli::pb_percent} [{cli::pb_elapsed}]",
                      show_after = 0,
                      clear = TRUE)
  )%>%
    purrr::list_rbind()
  
  return(res)
  
}

#First example - Pressed Esc in 33%
example_fun(c("a","b","c"))

#Second example - Run normally
example_fun(c("a","c"))
```

**Comment by hadley** [comment]
cc @gaborcsardi

**Comment by gaborcsardi** [comment]
Yeah, there are two ways to fix this afaict.  First is by adding cleancall support to purrr, i.e. embedding cleancall.{h,c} into purrr, and using it instead of `.Call`. Then this will be called: https://github.com/r-lib/cli/blob/bc503509cddb65d0007aeb301936e27de76bc7d7/inst/include/cli/progress.h#L299
https://github.com/r-lib/cli/tree/bc503509cddb65d0007aeb301936e27de76bc7d7/tests/testthat/progresstest has an example.

Second is to implement an exit handler in purrr itself, without cleancall.
