### ISSUE TITLE
Builds are failing on `R 3.4`

### ISSUE THREAD

**Issue by AshesITR** [tidyverse/purrr#1025]
Builds are failing on `R 3.4` because of `{purrr}`. No idea why.

```r
 ✖ Failed to build purrr 1.0.0
  Error: 
  ! error in pak subprocess
  Caused by error in `stop_task_build(state, worker)`:
  ! Failed to build source package 'purrr'
```

_Originally posted by @IndrajeetPatil in https://github.com/r-lib/lintr/pull/1870#issuecomment-1361664719_

According to the DESCRIPTION, R 3.4 should be supported. I noticed purrr CI does not run on R 3.4
Can you confirm the R version dependency?

**Comment by hadley** [comment]
Since R 4.2 is out we only test on 3.5 and up (see details at https://www.tidyverse.org/blog/2019/04/r-version-support/). We don't bother to systematically bump the required R version in the DESCRIPTION (because it's rarely important), but we can do so here to make it clear than purrr only works with 3.5 and up.

**Comment by AshesITR** [comment]
Thanks, that would help. We're going to manually ignore purrr in our R 3.5 CI for lintr for now.
Out of curiosity: Is there a way to "correct" DESCRIPTION info post-publishing to CRAN or is the incorrect information locked in place now?

**Comment by hadley** [comment]
No, we'll have to do another purrr release to fix the issue (which we're planning for in early January).
