### ISSUE TITLE
`map()` and `pmap()` remove class from error

### ISSUE THREAD

**Issue by jennybc** [tidyverse/purrr#1027]
I noticed this when googledrive had a test failure, where the function in question uses a `tryCatch()`:

https://github.com/tidyverse/googledrive/blob/7e8fa7abcb220566d2e1e99621b6e5d41e8f1c5b/R/shortcut.R#L184-L187

This `resolve_one()` function ultimately gets called inside `pmap()` and as of v1.0.0, the error no longer has the expected class.

---

With purrr 0.3.5, the class of an error thrown by `.f` is preserved. Here it's an `oops_error`.

``` r
f <- function(x) {
  if (x) {
    cli::cli_abort("oops", class = "oops_error")
  }
  x
}
f(FALSE)
#> [1] FALSE
f(TRUE)
#> Error in `f()`:
#> ! oops

#> Backtrace:
#>     ▆
#>  1. └─global f(TRUE)
#>  2.   └─cli::cli_abort("oops", class = "oops_error")
#>  3.     └─rlang::abort(...)

packageVersion("purrr")
#> [1] '0.3.5'

purrr::map(c(FALSE, TRUE), f)
#> Error in `.f()`:
#> ! oops

#> Backtrace:
#>     ▆
#>  1. └─purrr::map(c(FALSE, TRUE), f)
#>  2.   └─global .f(.x[[i]], ...)
#>  3.     └─cli::cli_abort("oops", class = "oops_error")
#>  4.       └─rlang::abort(...)
err <- rlang::catch_cnd(purrr::map(c(FALSE, TRUE), f))
err
#> <error/oops_error>
#> Error in `.f()`:
#> ! oops
#> ---
#> Backtrace:
#>  1. rlang::catch_cnd(purrr::map(c(FALSE, TRUE), f))
#>  8. purrr::map(c(FALSE, TRUE), f)
#>  9. global .f(.x[[i]], ...)
class(err)
#> [1] "oops_error"  "rlang_error" "error"       "condition"
```

---

But as of v1.0.0, the error no longer has that condition.

``` r
f <- function(x) {
  if (x) {
    cli::cli_abort("oops", class = "oops_error")
  }
  x
}
f(FALSE)
#> [1] FALSE
f(TRUE)
#> Error in `f()`:
#> ! oops

#> Backtrace:
#>     ▆
#>  1. └─global f(TRUE)
#>  2.   └─cli::cli_abort("oops", class = "oops_error")
#>  3.     └─rlang::abort(...)

packageVersion("purrr")
#> [1] '1.0.0'

purrr::map(c(FALSE, TRUE), f)
#> Error in `purrr::map()`:
#> ℹ In index: 2.
#> Caused by error in `.f()`:
#> ! oops

#> Backtrace:
#>     ▆
#>  1. └─purrr::map(c(FALSE, TRUE), f)
#>  2.   └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
#>  3.     ├─purrr:::with_indexed_errors(...)
#>  4.     │ └─base::withCallingHandlers(...)
#>  5.     └─global .f(.x[[i]], ...)
#>  6.       └─cli::cli_abort("oops", class = "oops_error")
#>  7.         └─rlang::abort(...)
err <- rlang::catch_cnd(purrr::map(c(FALSE, TRUE), f))
err
#> <error/rlang_error>
#> Error in `purrr::map()`:
#> ℹ In index: 2.
#> Caused by error in `.f()`:
#> ! oops
#> ---
#> Backtrace:
#>   1. rlang::catch_cnd(purrr::map(c(FALSE, TRUE), f))
#>   8. purrr::map(c(FALSE, TRUE), f)
#>   9. purrr:::map_("list", .x, .f, ..., .progress = .progress)
#>  12. global .f(.x[[i]], ...)
class(err)
#> [1] "rlang_error" "error"       "condition"
```

**Comment by hadley** [comment]
Yeah, because it's wrapped inside another error now.

**Comment by jennybc** [comment]
Does that mean this is a behavioural change that's here to stay?

I understand the intent of this to be to re-throw the error, but with extra info about the offending element:

https://github.com/tidyverse/purrr/blob/54546b6bf938c54da4d232061db2fc91b1d5923c/R/map.R#L205

**Comment by lionel-** [comment]
I think we may need to implement in `try_fetch()` the same behaviour as in `expect_error()`, i.e. matching across the `parent` ancestry of the condition.

Currently you need to implement this behaviour manually using `cnd_inherits()`:

```r
foo <- function() abort("foo", class = "foo")

# Using `try_fetch()` to easily return a value or ignore the condition
try_fetch(
  purrr::map(1, \(x) foo()),
  # Inspect all errors
  error = function(cnd) {
    if (cnd_inherits(cnd, "foo")) {
      # We got a match, return a value
      class(cnd)
    } else {
      # Ignore the ones that don't match
      zap()
    }
  }
)
#> [1] "rlang_error" "error"       "condition"
```

If `try_fetch()` supported this natively, this would be:

```r
try_fetch(
  purrr::map(1, \(x) foo()),
  foo = function(cnd) class(cnd)
)
```

**Comment by lionel-** [comment]
oops, the complicated `try_fetch()` call is not even right. Using `cnd_inherits()` to find out if there is a match is not sufficient, because we still have the child error in `cnd` and we want the parent error. Here is a working version:

```r
try_fetch(
  purrr::map(1, \(x) foo()),
  error = function(cnd) {
    repeat {
      if (is_null(cnd)) {
        return(zap())
      }
      if (inherits(cnd, "foo")) {
        return(class(cnd))
      }
      cnd <- cnd[["parent"]]
    }
  }
)
#> [1] "foo"         "rlang_error" "error"       "condition"
```

**Comment by hadley** [comment]
We’re likely to provide a way out of the error wrapping in a patch release in early Jan.

**Comment by lionel-** [comment]
Just to be clear, disabling the error wrapping only helps when you don't want the error wrapping, i.e. no index iteration info in error messages. It'd still be helpful to support parent errors in `try_fetch()` for the other cases. Also it's not possible to disable error wrapping in full generality, for instance in dplyr verbs.

**Comment by mlane3** [comment]
> Just to be clear, disabling the error wrapping only helps when you don't want the error wrapping, i.e. no index iteration info in error messages. It'd still be helpful to support parent errors in `try_fetch()` for the other cases. Also it's not possible to disable error wrapping in full generality, for instance in dplyr verbs.
I just mentioned this because lionel, point error wrapping being needed is really important.

**Comment by gadenbuie** [comment]
I think it'd be helpful to call this out in the NEWS as a breaking change. I think it'd also be worth calling out `rlang::cnd_inherits()` as a workaround, noting that the underlying error is now the parent of the thrown error. In my experience so far, I mostly need to move classed error handling via `tryCatch()` into the `error` handler to use `rlang::cnd_inherits()` instead.

Code from before purrr 1.0.0

``` r
abort_special <- function(x) rlang::abort("my error", class = "error_special")

## purrr <= 0.3.5 ----
tryCatch(
  purrr::map(1, abort_special),
  error_special = function(cnd) {
    message("handling special error...")
    cnd
  }
)
#> handling special error...
#> <error/error_special>
#> Error in `.f()`:
#> ! my error
#> ---
#> Backtrace:
#>  1. base::tryCatch(...)
#>  5. purrr::map(1, abort_special)
#>  6. global .f(.x[[i]], ...)
```

now becomes the following

```r
## purrr >= 1.0.0 ----
tryCatch(
  purrr::map(1, abort_special),
  error = function(cnd) {
    if (rlang::cnd_inherits(cnd, "error_special")) {
      message("handling special error...")
      cnd$parent
    }
  }
)
#> handling special error...
#> <error/error_special>
#> Error in `.f()`:
#> ! my error
#> ---
#> Backtrace:
#>  1. base::tryCatch(...)
#>  5. purrr::map(1, abort_special)
#>  6. purrr:::map_("list", .x, .f, ..., .progress = .progress)
#>  9. global .f(.x[[i]], ...)
```

If the message handler doesn't need to access data in the underlying error (i.e. taking out `cnd` and `cnd$parent` from the handlers above), both methods are equivalent and the second pattern will also work for purrr < 1.0.0.

**Comment by hadley** [comment]
Sounds like this issue needs three things:

1. An update to the NEWS to clearly indicate this breaking change
2. A way to opt-out
3. Some documentation about how to work around if you want to keep the iteration number (i.e. probably a custom error class and some docs around using `cnd_inherits`)

**Comment by hadley** [comment]
@gadenbuie there's a subtle error in your code. I think you want:

```R
tryCatch(
  purrr::map(1, abort_special),
  error = function(cnd) {
    if (rlang::cnd_inherits(cnd$parent, "error_special")) {
      message("handling special error...")
      cnd$parent
    } else {
     stop(cnd)
    }
  }
)
```

Otherwise other errors will be silently swallowed.

**Comment by lionel-** [comment]
@gadenbuie Also `tryCatch()` has big downsides for rethrowing errors. It prevents `recover()` and backtrace capture from reaching in the nested context. For this reason it's always preferable to use `withCallingHandlers()` or `try_fetch()` for the use case of rethrowing errors.

**Comment by mlane3** [comment]
@lionel- @hadley @gadenbuie   There is also the potential _fatal error_ that the code posted above could supress.

1) When I tried using the code above it reproduce the same weird rlang/vctrs same error that occured with prophet.  I suspect a reinstall of every single R package as before will fix the issue. 
 https://www.youtube.com/watch?v=tz5PIVs6QPQ

2)  At my work we have had similar but more fatal bug with due to .Rprofile and Onedrive.  I was able to trace the bug down to parent.frame() and what I suspect is .Rprofile before it ran cold. 
 https://community.rstudio.com/t/how-do-i-save-a-image-in-my-current-environment-not-global/153757/7?u=rgis
 https://community.rstudio.com/uploads/default/original/3X/d/e/de7545ff051ed919f01c234a59e32c912e5c9319.jpeg
 
 I think @lionel- re-traceability is very important.  Which is why I think this is almost a patch but not for all operating systems but not for Windows Server and I would be cautious about using this on Windows 11.

**Comment by mlane3** [comment]
At my work we have had similar but more fatal bug with due involving .Rprofile and Onedrive. I was able to trace the bug down to parent.frame() and what I suspect is .Rprofile before it ran cold because the operating system crashed due to Onedrive.
https://community.rstudio.com/t/how-do-i-save-a-image-in-my-current-environment-not-global/153757/7?u=rgis
image

@gadenbuie Also tryCatch() has big downsides for rethrowing errors. It prevents recover() and backtrace capture from reaching in the nested context. For this reason it's always preferable to use withCallingHandlers() or try_fetch() for the use case of rethrowing errors.

I think @lionel- re-traceability is very important. Which is why I think this is almost a patch but not for all operating systems but not for Windows Server and I would be cautious about using this on Windows 11.

**Comment by mlane3** [comment]
In truth @hadley I think what @lionel- @gadenbuie and @DavisVaughan discovered is a very old problem that streches way beyond purrr.   I have been tracking errors in .Rprofile, .RData, .Rhistory, and internet.c for the better part of a year. 
This was the first post I ever made on the topic: 
[https://community.rstudio.com/t/r-not-installing-properly-in-default-folders-corrupted-improper-installation/95956]( https://community.rstudio.com/t/r-not-installing-properly-in-default-folders-corrupted-improper-installation/95956)
 
3.  Due to long standing problems like in the above link, I think that a better debug package is needed for all tidyverse packages and Rstudio.  

Something that does a couple of things.

1. **Has a Day-Zero Debug mode** similar to RServe version of Rserve.exe that is updated.  In other words it as a docker container that can be opened by .Rexe and then will check the operating system for common errors.  It does not require R or Rstudio to work properly on the computer it is installed on.  So that it can print error logs and operating system setup information. 
2. Has better bebugs using recover, debugonce, tryFetch simialr to what @lionel-  is suggesting. 
3.  Depreciates the current rlang functions for error checking.  These don't work in most fatal R situations or when calling R from python. 
4.  Check files that the developer who asks to check are installed, have read permissions, and are accessible.  Warns the user about compatibility issues. (Warning does not display once)
5. Checks the install location of .Rprofile, .Rdata, .Rhistory are installed, have read permissions, and are accessible.  Warns the user about compatiblity issues.  (Warning does not display once as these warns are there to prevent fatal errors)
6. Recheck the install of number 4 if called by the user.
7.  Warns the user if anything using R-related is installed on Google Drive or One Drive
8.  Checks to make sure internet.c actually works.  Is the file stable and matches that currect version. 
9. Is rlang, vctrs independent of large packages. Mostly we are talking about having its own version of internet.c and parent.frame.  This is to allow the package to have stand-alone debugging of rlang and vctrs. 
10. Does not require the user to have to read Advanced R or the C source code to know what the problem is.

**Comment by hadley** [comment]
@mlane3 please don't `@` mention people in your replies. You have failed to clearly explain what your problem is and your large number of comments on the purrr repo are not helping. As an open source team, we only have a limited amount of time to focus on problems, like this, that only appear to affect a very small number of individuals.
