### ISSUE TITLE
accumulate_n

### ISSUE THREAD

**Issue by garrettgman** [tidyverse/purrr#394]
This parallels #253: it is useful to make a vector by applying a function recursively to an initial input for a set number of times. For example, you could use this to simulate a random walk or another type of martingale. 

Riffing on @dgrtwo's code, `accumulate_n()` would look something like this:
```
accumulate_n <- function(.x, .f, .n, ...) {
  .f <- as_function(.f, ...)

  ret <- vector("list", .n)
  ret[[1]] <- .x

  so_far <- .x

  for (i in seq(2, .n)) {
    result <- .f(so_far)
    ret[[i]] <- result
    so_far <- result
  }

  ret
}
````

This is easy to do in a for loop, but it is hard to pass that for loop to another function.  The idea came up today while working with @jkr216.

**Comment by lionel-** [comment]
I think this might be out of scope for purrr because it is easy to do this pattern by reducing over an index vector. This is similar to how you can map over an index vector, ignoring inputs:

```r
invisible(map(1:10, ~ cat("I'm run 10 times\n")))
#> I'm run 10 times
#> I'm run 10 times
#> I'm run 10 times
#> I'm run 10 times
#> I'm run 10 times
#> I'm run 10 times
#> I'm run 10 times
#> I'm run 10 times
#> I'm run 10 times
#> I'm run 10 times
```

You can in the same fashion reduce over an index vector and ignore the indices. To do this, you must supply an initial value which will be passed as the first result-so-far, on the LHS. Then index values are passed as new inputs on the RHS and you simply ignore them (or use those to give feedback to users via messages). All subsequent values returned from the function (the result-so-far) are passed on the LHS, giving a nice structure to the problem. Here is how to perform a random walk starting from 100:

```r
reduce(1:10, ~ rnorm(1, .x), .init = 100)
#> [1] 105.2511

accumulate(1:10, ~ rnorm(1, .x), .init = 100)
#> [1] 100.00000  97.18608  97.01237  96.74068  97.99936  96.72281  96.99919
#> [8]  96.36511  95.08154  94.46318  93.53628
```

I'm going to add this example to the documentation.
