### ISSUE TITLE
purrr::map() causes stats::update() to fail

### ISSUE THREAD

**Issue by jdobres** [tidyverse/purrr#407]
I was building a model incrementally (for demonstration purposes), and wanted to use `map` along with `update` to save myself some typing. I discovered that purrr is doing something to the function it's passed that causes `update` to fail. Example code:

```rm(list = ls())
library(tidyverse)

set.seed(1222)
data.ex <- tibble(
  y = 1:10,
  x1 = runif(10)
)

# Using update() outside of purrr works fine:
model <- lm(y ~ x1, data = data.ex)
model.new <- update(model) # no changes, but returns a "new" model, as expected

# purrr fails to preserve model info, causing update() to fail
# Error is 'update.default(.$model1) : need an object with call component'
model.purrr <- nest(data.ex, y, x1) %>%
  mutate(model1 = map(data, ~lm(y ~ x1, data = .x))) %>%
  do({
    return(update(.$model1)) # fails
  }) %>%
  mutate(model2 = map(data, function(x) update(x))) # fails
  mutate(model2 = map(model1, update)) #fails


```

**Comment by cderv** [comment]
The issue seems to be a little tricky here. Note that it works if you play with how `map` works. Here is how based on your example.
``` r
reprex::reprex_info()
#> Created by the reprex package v0.1.1.9000 on 2017-11-10

library(tidyverse)

set.seed(1222)
data.ex <- tibble(
  y = 1:10,
  x1 = runif(10),
  x2 = runif(10)
)

model <- lm(y ~ x1, data = data.ex)
model
#> 
#> Call:
#> lm(formula = y ~ x1, data = data.ex)
#> 
#> Coefficients:
#> (Intercept)           x1  
#>       7.128       -3.849
model.new <- update(model) 
model.new
#> 
#> Call:
#> lm(formula = y ~ x1, data = data.ex)
#> 
#> Coefficients:
#> (Intercept)           x1  
#>       7.128       -3.849
```

As you see a model object contains a call, with formula and data. How does it works inside `map` ? 
You'll see with `model1` result that, as you call `lm` inside map using `.x`, the call in the `lm` object  is looking for `data = .x`. In your different test, you did not provide `.x` that exists only because of `map` behaviour. It is not found automatically and correctly.
What if I use `map2` to provide 2 arguments:  first `data` column to already existing `purrr`'s `.x` in the formula and then use the second unamed arg `.y` in `update` to provide for the model object `model1` ?
(`map2` is like map but allows to iterate over 2 lists).
You can see it works - see `model2`. I also provide `model3` to test for a modification of the model. 

```r
model.purrr <- nest(data.ex) %>%
  mutate(model1 = map(data, ~ lm(y ~ x1, data = .x))) %>%
  mutate(model2 = map2(data, model1, ~ update(.y))) %>%
  mutate(model3 = map2(data, model1, ~ update(.y, . ~ x2 - 1)))

model.purrr$model1[[1]]
#> 
#> Call:
#> lm(formula = y ~ x1, data = .x)
#> 
#> Coefficients:
#> (Intercept)           x1  
#>       7.128       -3.849
model.purrr$model2[[1]]
#> 
#> Call:
#> lm(formula = y ~ x1, data = .x)
#> 
#> Coefficients:
#> (Intercept)           x1  
#>       7.128       -3.849
model.purrr$model3[[1]]
#> 
#> Call:
#> lm(formula = y ~ x2 - 1, data = .x)
#> 
#> Coefficients:
#>    x2  
#> 10.05
```

This is all because of how `purrr` and `map` functions works with `~ ` and `.x` call. Likely, using `pmap` can force to be explicit as you can provide a tibble and match columns to arguments in function by name like this: 
``` r
reprex::reprex_info()
#> Created by the reprex package v0.1.1.9000 on 2017-11-11

library(tidyverse)

set.seed(1222)
data.ex <- tibble(
  y = 1:10,
  x1 = runif(10),
  x2 = runif(10)
)

model.purrr <- nest(data.ex) %>%
  mutate(model1 = pmap(., function(data) lm(y ~ x1, data = data))) %>%
  mutate(model2 = pmap(., function(data, model1) update(model1))) %>%
  mutate(model3 = pmap(., function(data, model1, ...) update(model1, . ~ x2 - 1)))

model.purrr$model1[[1]]
#> 
#> Call:
#> lm(formula = y ~ x1, data = data)
#> 
#> Coefficients:
#> (Intercept)           x1  
#>       7.128       -3.849
model.purrr$model2[[1]]
#> 
#> Call:
#> lm(formula = y ~ x1, data = data)
#> 
#> Coefficients:
#> (Intercept)           x1  
#>       7.128       -3.849
model.purrr$model3[[1]]
#> 
#> Call:
#> lm(formula = y ~ x2 - 1, data = data)
#> 
#> Coefficients:
#>    x2  
#> 10.05
```
You'll see explicitly that we provide `data` column to each function because our model formula needs it. It is like a call `with(data, lm(y~x1))` but inside `purrr`.

Hopes it helps and it was not to cryptic.

Also, for working with model in the _tidyverse_ , you can look into [`modelr`](https://github.com/tidyverse/modelr). It is available officially in the `tidyverse` toolbox (with `install.packages("tidyverse")`). Do not know if you can update model easily though but you may find it interesting.

**Comment by jdobres** [comment]
Thanks for the clear explanation! It's certainly a tricky use case. I'm glad there's a way to make it work, but having to re-pass the original data frame to `update`, and moreover, having this provided argument picked up _implicitly_ by the modeling function, which is inside `update`, which is inside `map`, seems like a bug. I wonder if `map` could be modified to avoid the problem.

**Comment by hadley** [comment]
Unfortunately IMO the bug here lies with `update()`, not with purrr.  The `stats:::update.default()` re-evaluates the model in the `parent.frame()`, not the environment in which the model was originally fit.
