### ISSUE TITLE
possibbly fails on otherwise argument not quoted

### ISSUE THREAD

**Issue by pgensler** [tidyverse/purrr#409]
I'm not sure if this is a bug, but this seems to be related:
https://github.com/tidyverse/purrr/issues/173

Some of the docs examples make it seem like it is OK to not quote the otherwise argument, and be fine:

list("a", 10, 100) %>%
  map_dbl(possibly(log, NA_real_))

Example:
```
> sample_data <- tibble::tibble(
+   link = c("https://www.ratebeer.com/beer/pollyanna-eleanor-with-vanilla-beans/390639/",
+            "https://www.ratebeer.com/beer/brickstone-apa/99472/",
+            "https://www.ratebeer.com/beer/penrose-taproom-ipa/361258/",
+            "https://www.wrong-url.foobar")
+ )
> 
> #Function
> get_brewer_name <- function(url){
+   read_html(url) %>%
+     html_nodes(., xpath = c('//*[(@id = "_brand4")]//span')) %>%
+     html_text()
+ }
> ##This works
> final_data <- sample_data %>%
+   mutate(., brewer_name = map_chr(sample_data$link, possibly(get_brewer_name,otherwise="NULL"))) %>%
+   print(final_data)
# A tibble: 4 x 2
                                                                        link                     brewer_name
                                                                       <chr>                           <chr>
1 https://www.ratebeer.com/beer/pollyanna-eleanor-with-vanilla-beans/390639/       Pollyanna Brewing Company
2                        https://www.ratebeer.com/beer/brickstone-apa/99472/ Brickstone Restaurant & Brewery
3                  https://www.ratebeer.com/beer/penrose-taproom-ipa/361258/         Penrose Brewing Company
4                                               https://www.wrong-url.foobar                            NULL
> 
> 
> ##Yet this throws an error
> final_data <- sample_data %>%
+   mutate(., brewer_name = map_chr(sample_data$link, possibly(get_brewer_name,otherwise=NULL))) %>%
+   print(final_data)
Error in mutate_impl(.data, dots) : 
  Evaluation error: Result 4 is not a length 1 atomic vector.
```

**Comment by cderv** [comment]
Here is a smaller reprex with the url that do not work. 
``` r
reprex::reprex_info()
#> Created by the reprex package v0.1.1.9000 on 2017-11-11

library(purrr)
library(rvest)
#> Le chargement a nécessité le package : xml2
#> 
#> Attachement du package : 'rvest'
#> The following object is masked from 'package:purrr':
#> 
#>     pluck
url <- "https://www.wrong-url.foobar"
get_brewer_name <- function(url){
  read_html(url) %>%
    html_nodes(., xpath = c('//*[(@id = "_brand4")]//span')) %>%
    html_text()
}
get_brewer_name(url)
#> Error in open.connection(x, "rb"): Could not resolve host: www.wrong-url.foobar
possibly(get_brewer_name, otherwise = NULL)(url)
#> NULL
possibly(get_brewer_name, otherwise = "NULL")(url)
#> [1] "NULL"
```
It shows that is not a `purrr` issue with `possibly`. It works fine. 
Problem is in the choice of the `NULL` value in `otherwise` and how `map_chr` behave with `NULL`. If you had choose `NA`, i would have worked. Using `"NULL"`, it works because it is character.
``` r
reprex::reprex_info()
#> Created by the reprex package v0.1.1.9000 on 2017-11-11


library(dplyr, warn.conflicts = F)
library(rvest, warn.conflicts = F)
#> Le chargement a nécessité le package : xml2
library(purrr, warn.conflicts = F)
sample_data <- tibble::tibble(
  link = c("https://www.ratebeer.com/beer/pollyanna-eleanor-with-vanilla-beans/390639/",
           "https://www.ratebeer.com/beer/brickstone-apa/99472/",
           "https://www.ratebeer.com/beer/penrose-taproom-ipa/361258/",
           "https://www.wrong-url.foobar")
)

get_brewer_name <- function(url){
  read_html(url) %>%
    html_nodes(., xpath = c('//*[(@id = "_brand4")]//span')) %>%
    html_text()
}

final_data <- sample_data %>%
  mutate(., brewer_name = map_chr(sample_data$link, possibly(get_brewer_name,otherwise = NA)))
print.data.frame(final_data)
#>                                                                         link
#> 1 https://www.ratebeer.com/beer/pollyanna-eleanor-with-vanilla-beans/390639/
#> 2                        https://www.ratebeer.com/beer/brickstone-apa/99472/
#> 3                  https://www.ratebeer.com/beer/penrose-taproom-ipa/361258/
#> 4                                               https://www.wrong-url.foobar
#>                       brewer_name
#> 1       Pollyanna Brewing Company
#> 2 Brickstone Restaurant & Brewery
#> 3         Penrose Brewing Company
#> 4                            <NA>
```

So why the error ?  because `map_chr` must give a result as character vector or an error. `NULL` is not a character and could not be coerce to one.
``` r
reprex::reprex_info()
#> Created by the reprex package v0.1.1.9000 on 2017-11-11

library(purrr)
# map gives a list
list("A", NULL, "C") %>% map(identity)
#> [[1]]
#> [1] "A"
#> 
#> [[2]]
#> NULL
#> 
#> [[3]]
#> [1] "C"
# map_chr try to give a charater vector but fails
list("A", NULL, "C") %>% map_chr(identity)
#> Error: Result 2 is not a length 1 atomic vector
# because NULL is character(0)
as.character(NULL)
#> character(0)
# and length is 0
length(as.character(NULL))
#> [1] 0
```
Hence the error you get  : 
> Result 4 is not a length 1 atomic vector.
because you said explicitly to `otherwise` return `NULL`, but it does not fit with `map_chr`. 

So use `NA` (and precisely here `NA_character_`) for this kind of use case.
 `NULL` represents the NULL object whereas `NA` represents a missing value. It is why it is also typed and can be coerced.

**Comment by pgensler** [comment]
At the very least, if you supplied NULL with map_chr unquoted, at least tell the user that they need to quote it rather than stating it can't operate on it.

**Comment by cderv** [comment]
I don't think it is a problem of quoting.  (I explained it after)
It is rather a question of behavior of `purrr` with `NULL` value. It could be adapted to be less strict and not throws an error, but not sure it is a good idea. 

It is an API behavior discussion that I will let you have with rstudio team - in relation with the issue you linked.

I just wanted to give a working solution and help understand the current behavior for future reference.


---

`map_chr` does not require you to quote `NULL`, it just require that the iteration returns character element. SO, I don't think that its is on `purrr`'s hand. You can't use `NULL` either in vector with base R because a vector must contains element of same types, and `NULL` is not character here: 
``` r
vec <- c("A", NULL, "C")
vec
#> [1] "A" "C"
```
List can contain `NULL` elements and `map` returns them. I would say `map_*`  family functions are typed secure. the [doc](http://purrr.tidyverse.org/reference/map.html) explains it : 
>The map function transform the input, returning a vector the same length as the input. map() returns a list or a data frame; map_lgl(), map_int(), map_dbl() and map_chr() **return vectors of the corresponding type (or die trying)**;

`map_chr` returns a character vector _(or die trying)_. `NULL` is special. It has its own type and it is not character. When you quote `NULL` as `"NULL"`, you just create a string. It is of type character, but it is not the `NULL` value. 
``` r
typeof(NULL)
#> [1] "NULL"
typeof("NULL")
#> [1] "character"
is.null(NULL)
#> [1] TRUE
is.null("NULL")
#> [1] FALSE
```

**Comment by pgensler** [comment]
@cderv I 1000% agree with what you are saying.  What I'm saying is that I would never expect 
```
> length(NULL)
[1] 0
```
to be the culprit behind issues like:
https://github.com/tidyverse/purrr/issues/181
which yield confusing errors:
> #> Error: Result 1 is not a length 1 atomic vector

To me, this is an assignment error, which does not make sense. I can't replace a single element with another element?

If, in my example the reason my code fails is because of failing to quote the otherwise argument, then maybe purrr should be a bit more strict with the type specific functions:

I know it's somewhat a stretch case, but you don't want a char value in a dbl column so something like this should be illegal:

```
library(purrr)

my_func <- function(x){
  x^2
}

#valid vector
vec <- c(1,2,3,4)
is.vector(vec)
#we should try to protect against things like this
map_dbl(possibly(my_func, NA_character_) vec)

```
