### ISSUE TITLE
Reduce order of evaluation with piping produces different result

### ISSUE THREAD

**Issue by ybryan** [tidyverse/purrr#422]
I am confused as to why this produces two different results. I would expect them to produce the same result (the second one is "correct"). Does the reduce step create some temporary data structure that I'm not aware of or is the pipe operator performing some unknown effect?

```r
> reduce(as.list(1:4), sum) + reduce(as.list(1:4), sum) %>% sqrt()
[1] 13.16228
> sqrt(reduce(as.list(1:4), sum) + reduce(as.list(1:4), sum))  # sqrt(20)
[1] 4.472136
```

**Comment by lionel-** [comment]
This is because of operator precedence. `%>%` binds more tightly than `+` so the implicit parenthetical grouping goes as follow: `(a + (b %>% c))`. You can use `lobstr::ast()` to inspect the call tree:

```r
lobstr::ast(a + b %>% c)
#> █─`+` 
#> ├─a 
#> └─█─`%>%` 
#>   ├─b 
#>   └─c 
```

**Comment by cderv** [comment]
This is something due to the way the `magrittr`'s pipe `%>%` works. You have to take care of precedence with other operators. In you example `reduce(as.list(1:4), sum) %>% sqrt()` is evaluated before then sum up (`+`) with `reduce(as.list(1:4), sum)` hence `10 + 3,16228`

In the [documentation of `%>%`](http://magrittr.tidyverse.org/reference/pipe.html#technical-notes), this is mentionned:
> Another note is that special attention is advised when using non-magrittr operators in a pipe-chain (+, -, $, etc.), as operator precedence will impact how the chain is evaluated. In general it is advised to use the aliases provided by magrittr

You have to use `(...)` or `{...}` for gouping operation or use `magrittr`'s special aliases as advised. For example, instead of  `+` in a pipe chain, you can use `add`. 

some example to show what I mean with your example code: 

``` r
library(purrr)
# %>% takes precedence over +
reduce(as.list(1:4), sum) + reduce(as.list(1:4), sum) %>% sqrt()
#> [1] 13.16228

x <- reduce(as.list(1:4), sum)
x
#> [1] 10
sqrt(x)
#> [1] 3.162278

x + x %>% sqrt()
#> [1] 13.16228
# 
( x + x ) %>% sqrt()
#> [1] 4.472136
{ x + x } %>% sqrt()
#> [1] 4.472136

# You can use special aliases in a pipe chain
x %>%
  magrittr::add(x) %>%
  sqrt()
#> [1] 4.472136

sqrt(reduce(as.list(1:4), sum) + reduce(as.list(1:4), sum))  # sqrt(20)
#> [1] 4.472136
```

Created on 2017-12-05 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).
