### ISSUE TITLE
Should `pluck<-` actually be `chuck<-`?

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/purrr#634]
I am not sure that `pluck()` and `pluck<-()` are consistent. `pluck()` returns `NULL` if the element does not exist, but `pluck<-()` throws an error. In that way, `pluck<-()` feels more like the counterpart to `chuck()`. 

I am not sure that `pluck<-()` should even exist, since `assign_in()` is very strict and requires that the plucked-location must exist. I am just arguing that is should be named `chuck<-()` instead.

``` r
library(purrr)

pluck(mtcars, "y")
#> NULL

chuck(mtcars, "y")
#> Error: Can't find name `y` in vector

# should this be `chuck<-`()?
pluck(mtcars, "y") <- 1 
#> Error: Can't find name `y` in vector

# this should be `pluck<-`() I think
mtcars$y <- 1

# what I think should be `chuck<-`() uses chuck() already
`pluck<-`
#> function (.x, ..., value) 
#> {
#>     assign_in(.x, list2(...), value)
#> }
#> <bytecode: 0x7f9558ae34e8>
#> <environment: namespace:purrr>
purrr:::assign_in
#> function (x, where, value) 
#> {
#>     chuck(x, !!!where)
#>     call <- reduce_subset_call(quote(x), as.list(where))
#>     call <- call("<-", call, value)
#>     eval_bare(call)
#>     x
#> }
#> <bytecode: 0x7f9558ae2790>
#> <environment: namespace:purrr>
```

<sup>Created on 2019-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by lionel-** [comment]
We considered this and thought the interface would be simpler overall this way because casual users wouldn't need to learn the difference between the two and remember that they have to use `chuck<-` rather than `pluck<-`. Note that a lenient `pluck<-` isn't possible because there is no type information for non-existing locations.

**Comment by lionel-** [comment]
Just got some feedback from @jennybc about `modify_in()` and `assign_in()`.

* `modify_in()` might need an option to ignore non-existing locations instead of failing.
* `assign_in()` might need an option to force assignment in non-existing locations (using lists for deep assignments where there is no type information? Or error in that case?).

The latter suggests we should have both `pluck<-` and `chuck<-`.

Also would be useful to have a `can_pluck()` predicate.

cc @hadley

**Comment by lionel-** [comment]
From @hadley:`can_pluck()` could be `has_element()`
