### ISSUE TITLE
man links out to rdocumentation, a datacamp site for httr::RETRY

### ISSUE THREAD

**Issue by alex-gable** [tidyverse/purrr#677]
It wasn't immediately obvious how this link was getting constructed differently as compared to other links in the `@seealso` block to point to rdocumentation.com as opposed to a site that isn't affiliated with datacamp. 

happy to make the changes necessary if you can help outline what needs to be done!

https://github.com/tidyverse/purrr/blob/9bd07059caa64117d51788d38d7d45e1096f2902/R/rate.R#L19

**Comment by batpigandme** [comment]
Hi @alex-gable,

So, this is currently the case with functions in other packages (as opposed to internal ones, like `insistently()`, which can link within the purrr documentation — or other package-specific documentation). Ideally, this would go to [`httr::RETRY()`](https://httr.r-lib.org/reference/RETRY.html), but we need a more generalized solution to make that happen. 

cc @hadley — I'm not sure where to put a general issue for this (tidytemplate?), since it's not purrr-specific. I think the solution will vary depending on whether it's a tidyverse/r-lib function vs. something else, since we can't reliably go to a pkgdown site for those.

**Comment by hadley** [comment]
The dev version of pkgdown points to rdrr.io instead of rdocumentation.

But but now that httr has a website, it should get a direct link. But the link in the dev version is still  wrong: https://purrr.tidyverse.org/dev/reference/insistently.html — oh, because httr on CRAN doesn't have a link to its website in the DESCRIPTION. That's also already fixed in the dev version.

**Comment by alex-gable** [comment]
thanks for looking into this y'all!
