### ISSUE TITLE
feature request: sorting/arranging

### ISSUE THREAD

**Issue by torbjorn** [tidyverse/purrr#761]
There are various sophisticated ways of mapping and filtering available, shouldn't there be sorting too? Or did I just not find it?

In my particulare case I'd like to do ``` my.list %>% arrange( ~ .x$foo )``` (ie arrange my list by the $foo value in each element)

**Comment by moodymudskipper** [comment]
I think you can do : `my.list %>% .[order(map_dbl(., "foo"))]`

But +1 anyway because sorting in R always seems harder than it should be.

**Comment by torbjorn** [comment]
Is there anything happening with this repo?

**Comment by lionel-** [comment]
We'll do some work on purrr after dplyr 1.0.

**Comment by lionel-** [comment]
Thanks for the suggestion. Since it is so easy to build your own helper for this (e.g. following @moodymudskipper's pattern), and so costly to add a function to purrr (more complex API and documentation, need to think about a good name that will be exposed by `library(tidyverse)`, ...), I think it's best not to add it in purrr at the moment.
