### ISSUE TITLE
Function working outside list, but not inside

### ISSUE THREAD

**Issue by iago-pssjd** [tidyverse/purrr#821]
Why the first example works but not the second?

``` r
library(tidyverse)
a <- 1:5

list(tibble(a, b = a * 2, c = 1)) %>% 
  map(.f = ~(filter(.x, if_all(last_col(), ~.==2)) %>% dim() %>% magrittr::extract(1)))
#> [[1]]
#> [1] 0

list(tibble(a, b = a * 2, c = 1)) %>% 
  map(.f = list(~(filter(.x, if_all(last_col(), ~.==2)) %>% dim() %>% magrittr::extract(1))))
#> Error: Index 1 must have length 1, not 2
```
<sup>Created on 2021-03-16 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Thank you!

**Comment by mutahiwachira** [comment]
In short, what's happening is that when you supply a list to map, it triggers a chain of functions which ultimately invoke pluck. Pluck doesn't like purrr's `~` notation. If you rewrite your second example with `function(x)` notation instead, then it 'works' (no error message). Here:

``` r
library(tidyverse)
a <- 1:5
list(tibble(a, b = a * 2, c = 1)) %>% 
  map(.f = list(function(.x) (filter(.x, if_all(last_col(), ~.==2)) %>% dim() %>% magrittr::extract(1))))
#> [[1]]
#> [1] 0
```

However, it's important to realize that when you supply a list to map, it handles it completely differently to when you just supply a function. So removing the `~` notation removes the bug but I wouldn't say it's correct, because it is not implementing the same function that you supplied. If you are familiar with how map() works internally, then skip to the conclusion.

Explainer - Using Lists in map()
------
The reason this is happening is because the underlying implementation of `map`, `as_mapper`, has a special method of handling lists.

### map is just a wrapper around as_mapper and call
``` r
purrr::map
#> function (.x, .f, ...) 
#> {
#>     .f <- as_mapper(.f, ...)
#>     .Call(map_impl, environment(), ".x", ".f", "list")
#> }
#> <bytecode: 0x0000000015e74d58>
#> <environment: namespace:purrr>
```

When you call map(.f, ...), it runs the function as_mapper to create a function which iterates over a list... and then it calls that new function on your list .x

### as_mapper usually takes naked functions, but has special methods for other inputs
If you look at the documentation for `as_mapper` [here](https://purrr.tidyverse.org/reference/as_mapper.html), it explains that the function usually just turns a normal function into a function that works on list. However, if you supply a character vector, numeric vector or a list, then what it does is it creates an extractor function:

> If character vector, numeric vector, or list, it is converted to an extractor function. Character vectors index by name and numeric vectors index by position; use a list to index by position and name at different levels. If a component is not present, the value of .default will be returned.

So, as in the example, if you take `as_mapper(1)` it will return an extractor function (using `purrr::pluck`) which extracts the first element of every list. You can even see this by just calling as_mapper(1) from the console:

``` r
purrr::as_mapper(1)
#> function (x, ...) 
#> pluck(x, 1, .default = NULL)
#> <environment: 0x0000000015e583c0>
```

When you call as_mapper() on a list, it will take each element of the list as an argument in pluck

``` r
purrr::as_mapper(list(1,2,3))
#> function (x, ...) 
#> pluck(x, 1, 2, 3, .default = NULL)
#> <environment: 0x0000000015e68a00>
```

Here is the as_mapper output for the list you are passing in your example. The function that as_mapper creates is what you are applying to your list of tibbles:

``` r
new_mapper <- purrr::as_mapper(list(~(filter(.x, if_all(last_col(), ~.==2)) %>% dim() %>% magrittr::extract(1))))
new_mapper
#> function (x, ...) 
#> pluck(x, ~(filter(.x, if_all(last_col(), ~. == 2)) %>% dim() %>% 
#>     magrittr::extract(1)), .default = NULL)
#> <environment: 0x0000000015ec9f60>
```

So this is the function you are applying, you are plucking from a list and the index your are plucking with is a formula object. If I dramatically simplify the pluck formula above, this is effectively what is happening:

``` r
purrr::pluck(list(4,5,6,7), 1) # typical use case
#> [1] 4
purrr::pluck(list(4,5,6,7), ~ .x[[1]]) # pluck with a formula
#> Error: Index 1 must have length 1, not 2
```

### So can pluck work with a formula?

The typical use case of pluck is that you supply numbers or names to index. The ultimate output from your map is that you are indexing with a formula, using the purrr syntax. The documentation for pluck actually mentions that you _can_ index with an accessor function:

``` r
purrr::pluck(list(4,5,6,7), 1)
#> [1] 4
purrr::pluck(list(4,5,6,7), ~ .x[[1]])
#> Error: Index 1 must have length 1, not 2
purrr::pluck(list(4,5,6,7), function(x) x[[1]])
#> [1] 4
```

The code above suggests that purrr can use functions to do its plucking, but not purrr-style formula notation.

This is why it works when you shift from using `~` to `function(x)`

Conclusion - Using list() in map
-----

Even though we can make it 'work' when using a list in map, it's important to note that the minute you supply a list() to map you are fundamentally changing the computation. Here is what `as_mapper` gives for the two different cases you supplied.

``` r
as_mapper(~(filter(.x, if_all(last_col(), ~.==2)) %>% dim() %>% magrittr::extract(1)))
#> <lambda>
#> function (..., .x = ..1, .y = ..2, . = ..1) 
#> (filter(.x, if_all(last_col(), ~. == 2)) %>% dim() %>% magrittr::extract(1))
#> attr(,"class")
#> [1] "rlang_lambda_function" "function"

as_mapper(list(function(.x) (filter(.x, if_all(last_col(), ~.==2)) %>% dim() %>% magrittr::extract(1)))) #working version of as_mapper(list(~(filter(.x, if_all(last_col(), ~.==2)) %>% dim() %>% magrittr::extract(1))))
#> function (x, ...) 
#> pluck(x, function (.x) 
#> (filter(.x, if_all(last_col(), ~. == 2)) %>% dim() %>% magrittr::extract(1)), 
#>     .default = NULL)
#> <environment: 0x0000000019afaaa8>
```

These are two different functions. I'm not sure whether they even mean the same thing, or whether it worked on your example just because of a fluke in the logic of the example. But it's certainly the cast that using `list()` inside of `map()` is not how you supply a list of functions to `map` - it will do something else. If someone wants to supply a list of functions to `map`, you should pass it in as something you are mapping over (the `.x`) and possibly use `map2` so that you can map over a set of data and a list. Then your .f would something like `do.call`.

**Comment by hadley** [comment]
Thanks for the detailed explanation @mutahiwachira!
